services:
  - type: web
    name: notetracker-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
