services:
  - type: web
    name: notetracker-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "mysql://user:pass@host:port/dbname" # Değiştirilmesi gerekiyor
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
