// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteTrackerApp.Data;

#nullable disable

namespace NoteTrackerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505202918_AddPerformanceLikesProjects")]
    partial class AddPerformanceLikesProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NoteTrackerApp.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.AnnouncementView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("AnnouncementViews");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanChangePhoto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecoveryPin")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanChangePhoto = true,
                            FullName = "Sistem Yöneticisi",
                            Password = "AQAAAAIAAYagAAAAEKt4/ok1SaFfB8xQs9jXJsx3gaFhXI3MfaSljdWDYIurNjnzwKRrewXSfcbgsL39Sg==",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("NoteTrackerApp.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeni Yıl",
                            Title = "Yılbaşı"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ulusal Egemenlik ve Çocuk Bayramı",
                            Title = "23 Nisan Ulusal Egemenlik ve Çocuk Bayramı"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emek ve Dayanışma Günü",
                            Title = "1 Mayıs İşçi Bayramı"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gençlik ve Spor Bayramı",
                            Title = "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Milli Birlik Günü",
                            Title = "15 Temmuz Demokrasi ve Milli Birlik Günü"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zafer Bayramı",
                            Title = "30 Ağustos Zafer Bayramı"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Türkiye Cumhuriyeti'nin Kuruluş Yıldönümü",
                            Title = "29 Ekim Cumhuriyet Bayramı"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mustafa Kemal Atatürk'ü saygı ve özlemle anıyoruz",
                            Title = "10 Kasım - Atatürk'ü Anma Günü"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2024-2025 eğitim-öğretim yılı başlar",
                            Title = "I. Dönem Başlangıcı"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1. Dönem sona erer",
                            Title = "I. Dönem Sonu"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2. Dönem başlar",
                            Title = "II. Dönem Başlangıcı"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2024-2025 eğitim öğretim yılı sona erer",
                            Title = "II. Dönem Sonu / Yıl Sonu"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ramazan Bayramı (3 Gün)",
                            Title = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kurban Bayramı (4 Gün)",
                            Title = "Kurban Bayramı"
                        });
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Average")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Exam1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Exam2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Oral1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Oral2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Performance1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Performance2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Project")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PerformanceCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Appearance")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HomeworkCompletion")
                        .HasColumnType("int");

                    b.Property<int>("MaterialReady")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Participation")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("PerformanceCriterias");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TargetClass")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsLike")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique()
                        .HasFilter("`CommentId` IS NOT NULL");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique()
                        .HasFilter("`PostId` IS NOT NULL");

                    b.ToTable("PostLikes");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostViews");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.ProjectAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DraftDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinalDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TeacherNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ProjectAssignments");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClassSection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.AnnouncementView", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Announcement", "Announcement")
                        .WithMany("Views")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Grade", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PerformanceCriteria", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Post", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostComment", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.PostComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NoteTrackerApp.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostLike", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.PostComment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId");

                    b.HasOne("NoteTrackerApp.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId");

                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostView", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Post", "Post")
                        .WithMany("Views")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.ProjectAssignment", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Student", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Announcement", b =>
                {
                    b.Navigation("Views");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostComment", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
