// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteTrackerApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoteTrackerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoteTrackerApp.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.AnnouncementView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("AnnouncementViews");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanChangePhoto")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RecoveryPin")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanChangePhoto = true,
                            FullName = "Sistem Yöneticisi",
                            Password = "AQAAAAIAAYagAAAAEFC5decMFzIm3rtwYChRLUm2ddcAsszOgnP5JgmW0/JbUsg4ragBL8/1Okeh5Tsp5w==",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("NoteTrackerApp.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeni Yıl",
                            Title = "Yılbaşı"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ulusal Egemenlik ve Çocuk Bayramı",
                            Title = "23 Nisan Ulusal Egemenlik ve Çocuk Bayramı"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Emek ve Dayanışma Günü",
                            Title = "1 Mayıs İşçi Bayramı"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gençlik ve Spor Bayramı",
                            Title = "19 Mayıs Atatürk'ü Anma, Gençlik ve Spor Bayramı"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Milli Birlik Günü",
                            Title = "15 Temmuz Demokrasi ve Milli Birlik Günü"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zafer Bayramı",
                            Title = "30 Ağustos Zafer Bayramı"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Türkiye Cumhuriyeti'nin Kuruluş Yıldönümü",
                            Title = "29 Ekim Cumhuriyet Bayramı"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mustafa Kemal Atatürk'ü saygı ve özlemle anıyoruz",
                            Title = "10 Kasım - Atatürk'ü Anma Günü"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2024-2025 eğitim-öğretim yılı başlar",
                            Title = "I. Dönem Başlangıcı"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1. Dönem sona erer",
                            Title = "I. Dönem Sonu"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2. Dönem başlar",
                            Title = "II. Dönem Başlangıcı"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2024-2025 eğitim öğretim yılı sona erer",
                            Title = "II. Dönem Sonu / Yıl Sonu"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ramazan Bayramı (3 Gün)",
                            Title = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kurban Bayramı (4 Gün)",
                            Title = "Kurban Bayramı"
                        });
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Average")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Exam1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Exam2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Oral1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Oral2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Performance1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Performance2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Project")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TargetClass")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostViews");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassSection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.AnnouncementView", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Announcement", "Announcement")
                        .WithMany("Views")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Grade", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Post", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostComment", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.PostView", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.Post", "Post")
                        .WithMany("Views")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Student", b =>
                {
                    b.HasOne("NoteTrackerApp.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Announcement", b =>
                {
                    b.Navigation("Views");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("NoteTrackerApp.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
